(define (problem printing_problem)
   (:domain printing_domain)
   (:objects
      Workpiece1 - PrintingWorkpiece
   )
   (:init
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_0)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_10)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_100)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_110)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_120)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_130)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_140)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_150)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_160)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_170)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_180)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_190)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_20)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_200)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_30)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_40)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_50)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_60)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_70)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_80)
      (canReachNozzleTemperature AnetA8v2 NozzleTemperature_90)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_0)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_10)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_100)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_110)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_120)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_130)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_140)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_150)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_160)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_170)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_180)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_190)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_20)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_200)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_210)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_220)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_230)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_240)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_250)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_30)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_40)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_50)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_60)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_70)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_80)
      (canReachNozzleTemperature PrusaMK3001 NozzleTemperature_90)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_0)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_10)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_100)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_110)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_120)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_130)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_140)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_150)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_160)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_170)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_180)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_190)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_20)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_200)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_210)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_220)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_230)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_240)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_250)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_30)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_40)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_50)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_60)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_70)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_80)
      (canReachNozzleTemperature PrusaMK3002 NozzleTemperature_90)
      (= (EnergyCost) 0.0)
      (= (EnergyEfficiency AnetA8v2) 1.2)
      (= (EnergyEfficiency PrusaMK3001) 1.0)
      (= (EnergyEfficiency PrusaMK3002) 1.0)
      (= (MachineUsage AnetA8v2) 0.0)
      (= (MachineUsage PrusaMK3001) 0.0)
      (= (MachineUsage PrusaMK3002) 0.0)
      (= (MaterialCost) 0.0)
      (= (MaterialEquationValue_CostMap ABS) 1.0)
      (= (MaterialEquationValue_CostMap PLA) 1.2)
      (= (NumericValuesFunction EstimatedPrintTime_120) 120.0)
      (= (NumericValuesFunction EstimatedPrintTime_150) 150.0)
      (= (NumericValuesFunction EstimatedPrintTime_180) 180.0)
      (= (NumericValuesFunction EstimatedPrintTime_210) 210.0)
      (= (NumericValuesFunction EstimatedPrintTime_240) 240.0)
      (= (NumericValuesFunction EstimatedPrintTime_270) 270.0)
      (= (NumericValuesFunction EstimatedPrintTime_30) 30.0)
      (= (NumericValuesFunction EstimatedPrintTime_300) 300.0)
      (= (NumericValuesFunction EstimatedPrintTime_330) 330.0)
      (= (NumericValuesFunction EstimatedPrintTime_360) 360.0)
      (= (NumericValuesFunction EstimatedPrintTime_390) 390.0)
      (= (NumericValuesFunction EstimatedPrintTime_420) 420.0)
      (= (NumericValuesFunction EstimatedPrintTime_450) 450.0)
      (= (NumericValuesFunction EstimatedPrintTime_480) 480.0)
      (= (NumericValuesFunction EstimatedPrintTime_510) 510.0)
      (= (NumericValuesFunction EstimatedPrintTime_540) 540.0)
      (= (NumericValuesFunction EstimatedPrintTime_570) 570.0)
      (= (NumericValuesFunction EstimatedPrintTime_60) 60.0)
      (= (NumericValuesFunction EstimatedPrintTime_600) 600.0)
      (= (NumericValuesFunction EstimatedPrintTime_630) 630.0)
      (= (NumericValuesFunction EstimatedPrintTime_660) 660.0)
      (= (NumericValuesFunction EstimatedPrintTime_690) 690.0)
      (= (NumericValuesFunction EstimatedPrintTime_720) 720.0)
      (= (NumericValuesFunction EstimatedPrintTime_750) 750.0)
      (= (NumericValuesFunction EstimatedPrintTime_780) 780.0)
      (= (NumericValuesFunction EstimatedPrintTime_810) 810.0)
      (= (NumericValuesFunction EstimatedPrintTime_840) 840.0)
      (= (NumericValuesFunction EstimatedPrintTime_870) 870.0)
      (= (NumericValuesFunction EstimatedPrintTime_90) 90.0)
      (= (NumericValuesFunction EstimatedPrintTime_900) 900.0)
      (= (NumericValuesFunction NozzleTemperature_0) 0.0)
      (= (NumericValuesFunction NozzleTemperature_10) 10.0)
      (= (NumericValuesFunction NozzleTemperature_100) 100.0)
      (= (NumericValuesFunction NozzleTemperature_110) 110.0)
      (= (NumericValuesFunction NozzleTemperature_120) 120.0)
      (= (NumericValuesFunction NozzleTemperature_130) 130.0)
      (= (NumericValuesFunction NozzleTemperature_140) 140.0)
      (= (NumericValuesFunction NozzleTemperature_150) 150.0)
      (= (NumericValuesFunction NozzleTemperature_160) 160.0)
      (= (NumericValuesFunction NozzleTemperature_170) 170.0)
      (= (NumericValuesFunction NozzleTemperature_180) 180.0)
      (= (NumericValuesFunction NozzleTemperature_190) 190.0)
      (= (NumericValuesFunction NozzleTemperature_20) 20.0)
      (= (NumericValuesFunction NozzleTemperature_200) 200.0)
      (= (NumericValuesFunction NozzleTemperature_210) 210.0)
      (= (NumericValuesFunction NozzleTemperature_220) 220.0)
      (= (NumericValuesFunction NozzleTemperature_230) 230.0)
      (= (NumericValuesFunction NozzleTemperature_240) 240.0)
      (= (NumericValuesFunction NozzleTemperature_250) 250.0)
      (= (NumericValuesFunction NozzleTemperature_30) 30.0)
      (= (NumericValuesFunction NozzleTemperature_40) 40.0)
      (= (NumericValuesFunction NozzleTemperature_50) 50.0)
      (= (NumericValuesFunction NozzleTemperature_60) 60.0)
      (= (NumericValuesFunction NozzleTemperature_70) 70.0)
      (= (NumericValuesFunction NozzleTemperature_80) 80.0)
      (= (NumericValuesFunction NozzleTemperature_90) 90.0)
   )
   (:goal (and
      (isPrinted Workpiece1)
   ))
   (:metric minimize(+ (* 1.0 (MaterialCost)) (* 2.0 (EnergyCost))))
)