(define (problem shared_production_problem)
   (:domain shared_production_domain)
   (:objects
      Workpiece1 - Workpiece
   )
   (:init
      (CanPrint PrusaKL ABS)
      (CanPrint PrusaKL PLA)
      (CanPrint PrusaLemgo ABS)
      (CanPrint PrusaLemgo PLA)
      (CanTransportBetween UR5eKL CameraKL PrusaKL)
      (CanTransportBetween UR5eKL CameraKL WarehouseKL)
      (CanTransportBetween UR5eKL PrusaKL CameraKL)
      (CanTransportBetween UR5eKL PrusaKL WarehouseKL)
      (CanTransportBetween UR5eKL WarehouseKL CameraKL)
      (CanTransportBetween UR5eKL WarehouseKL PrusaKL)
      (CanTransportBetween UR5eLemgo CameraLemgo PrusaLemgo)
      (CanTransportBetween UR5eLemgo CameraLemgo WarehouseLemgo)
      (CanTransportBetween UR5eLemgo PrusaLemgo CameraLemgo)
      (CanTransportBetween UR5eLemgo PrusaLemgo WarehouseLemgo)
      (CanTransportBetween UR5eLemgo WarehouseLemgo CameraLemgo)
      (CanTransportBetween UR5eLemgo WarehouseLemgo PrusaLemgo)
      (InFactory CameraKL SmartFactoryKL)
      (InFactory CameraLemgo SmartFactoryOWL)
      (InFactory PrusaKL SmartFactoryKL)
      (InFactory PrusaLemgo SmartFactoryOWL)
      (InFactory UR5eKL SmartFactoryKL)
      (InFactory UR5eLemgo SmartFactoryOWL)
      (InFactory WarehouseKL SmartFactoryKL)
      (InFactory WarehouseLemgo SmartFactoryOWL)
      (IsAvailable SmartFactoryKL)
      (IsAvailable SmartFactoryOWL)
      (IsReady CameraKL)
      (IsReady CameraLemgo)
      (IsReady PrusaKL)
      (IsReady PrusaLemgo)
      (IsReady UR5eKL)
      (IsReady UR5eLemgo)
      (= (CO2Efficiency SmartFactoryKL) 150.0)
      (= (CO2Efficiency SmartFactoryOWL) 100.0)
      (= (CO2EfficiencyWeight) 1.0)
      (= (CostEfficiency SmartFactoryKL) 100.0)
      (= (CostEfficiency SmartFactoryOWL) 150.0)
      (= (CostEfficiencyWeight) 1.0)
      (= (DeliveryCostWeight) 1.0)
      (= (DeliveryDelayCost) 100.0)
      (= (DeliveryTimeWeight) 1.0)
      (= (Distance CustomerLocation CustomerLocation) 0.0)
      (= (Distance CustomerLocation WarehouseKL) 85.0)
      (= (Distance CustomerLocation WarehouseLemgo) 285.0)
      (= (Distance WarehouseKL CustomerLocation) 85.0)
      (= (Distance WarehouseKL WarehouseKL) 0.0)
      (= (Distance WarehouseKL WarehouseLemgo) 300.0)
      (= (Distance WarehouseLemgo CustomerLocation) 285.0)
      (= (Distance WarehouseLemgo WarehouseKL) 300.0)
      (= (Distance WarehouseLemgo WarehouseLemgo) 0.0)
      (= (total-cost) 0.0)
   )
   (:goal (and
      (At Workpiece1 CustomerLocation)
      (IsMadeOf Workpiece1 PLA)
      (QualityChecked Workpiece1)
   ))
   (:metric minimize(total-cost))
)